### ISSUE TITLE
version that doesn't punch globals

### ISSUE THREAD

**Issue by ghost** [mathiasbynens/String.prototype.codePointAt#1]
This is really useful code but it punches the global `String.prototype.codePointAt`, which doesn't compose well (thrashing/breakage likely when multiple competing modules try to "fix" the same thing). Can we get a version of this that just does a module.exports= instead of mutating a global?

**Comment by mathiasbynens** [comment]
This module won’t actually do anything if _anything_ is already defined as `String.prototype.codePointAt`, so unless you `require` a broken `String#codePointAt` polyfill before this one, nothing breaks. Or did you mean something else?

For a separate module that does something similar, try [`punycode`](http://mths.be/punycode) (which ships with Node.js by default):

``` js
punycode.ucs2.decode('\uD834\uDF06')[0]
```
