### ISSUE TITLE
Publish new version with updated license file?

### ISSUE THREAD

**Issue by nali** [mathiasbynens/String.prototype.codePointAt#3]
The current release has a deprecated method of listing the license in the `package.json`, namely, a licenses property with an array of license objects. This has been updated in master but there hasn't been a new release since then; any change of getting a new version of this package with that `license` update in the package.json?

**Comment by mathiasbynens** [comment]
Sure thing! I just published v0.2.1.

**Comment by nali** [comment]
Thanks Mathias! 🤗
